# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-01 08:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='catalogue/products', verbose_name='image')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='Specs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(blank=True, null=True, verbose_name='weight, gr')),
                ('size', models.FloatField(blank=True, null=True, verbose_name='size')),
                ('price', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='price')),
                ('specs', models.TextField(blank=True, null=True, verbose_name='other specs')),
            ],
            options={
                'verbose_name': 'Specs',
                'verbose_name_plural': 'Specs',
            },
        ),
        migrations.RemoveField(
            model_name='item',
            name='price',
        ),
        migrations.AlterField(
            model_name='item',
            name='title_image',
            field=models.ImageField(upload_to='catalogue/products', verbose_name='title image'),
        ),
        migrations.AlterField(
            model_name='item',
            name='type',
            field=models.CharField(blank=True, choices=[('Men', 'Men'), ('Women', 'Women')], default='---------', max_length=9, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='specs',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item'),
        ),
        migrations.AddField(
            model_name='image',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Item', verbose_name='item'),
        ),
    ]
