# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-03-12 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20180205_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='sales',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='name',
            field=models.CharField(max_length=256, verbose_name='name'),
        ),
    ]
